apiVersion: apps/v1
kind: Deployment
metadata:
  name: toxiproxy
  namespace: tyk
  labels:
    app: toxiproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toxiproxy
  template:
    metadata:
      labels:
        app: toxiproxy
    spec:
      containers:
        - name: toxiproxy
          image: ghcr.io/shopify/toxiproxy:2.5.0
          args:
            - "-host=0.0.0.0"
          ports:
            - containerPort: 8474
              name: api
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /version
              port: api
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /version
              port: api
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: toxiproxy
  namespace: tyk
  labels:
    app: toxiproxy
spec:
  selector:
    app: toxiproxy
  ports:
    - name: api
      port: 8474
      targetPort: api
      protocol: TCP
  # in our local dev env cluster, cloud-provider-kind maps LB public IP to host
  type: LoadBalancer
